# Generated by Django 5.2.5 on 2026-06-15 11:24

from django.db import migrations, models


def blank_phone_to_null(apps, schema_editor):
    Account = apps.get_model('core', 'Account')
    Account.objects.filter(phone='').update(phone=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(blank_phone_to_null, migrations.RunPython.noop),
    ]
