# Generated by Django 5.2.5 on 2025-10-05 23:33

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('coordinate', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('hashid', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('assigned', 'Assigned'), ('en_route', 'En Route'), ('arrived', 'Arrived'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='scheduled', max_length=20)),
                ('customer_notes', models.TextField(blank=True, default='')),
                ('driver_notes', models.TextField(blank=True, default='')),
                ('dispatcher_notes', models.TextField(blank=True, default='')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_destination', to='trip.place')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='core.driver')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_origin', to='trip.place')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='core.rider')),
            ],
        ),
    ]
